### ISSUE TITLE
Qr not generated

### ISSUE THREAD

**Issue by Munnabhai9100** [iamherok/Cara_public#6]
Hey! I want to tell you that i am not able to generate qr after forking and changing readme repo deploy link or forking
But if i tries the orginal one it's not deploying 
Error-we couldn't deploy your app because the source code violated the Salesforce accepyable use and external facing service policy

**Comment by iamherok** [comment]
May be because of your mongodb url issue the qr is not generating and u can't deploy directly because heroku changed their policy so u need to foke the repo and change the readme
